gmhelper/gmhelper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("panel/", include("panel.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gmhelper/panel/urls.py
from django.urls import path
from panel import session
from panel import views

urlpatterns = [
    path("auto_complete", views.auto_complete),
    path("client", views.client),
    path("controls", views.controls),
    path("info_card", views.info_card),
    path("songs", views.songs),
    path("display_item", views.display_item),
    path("update_session", session.update),
    path("session_content", session.content),
    path("save_session", session.save),
    path("edit_session", session.edit),
    path("update_item_order", session.update_item_order)
]

gmhelper/panel/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from gm2m import GM2MField

class Tag(models.Model):
  """An abstract class for classifying data items."""
  name = models.CharField(max_length=64)
  flavor = models.TextField(default=None, blank=True)

  def __str__(self):
    return self.name

class DataItem(models.Model):
  """Abstract super class for all data items. Contains name & flavor only."""
  name = models.CharField(max_length=255)
  flavor = models.TextField(default=None, blank=True)

  def __str__(self):
    return self.name

  class Meta:
    abstract = True

class Letter(DataItem):
  """Represents a letter the players receive.

  The name flavor and author of the letter will be private information, only the
  text of the letter will be displayed to the client.
  """
  author = models.CharField(max_length=255)
  text = models.TextField()
  items = GenericRelation("SessionItem", related_query_name="letter")

class Lore(DataItem):
  """A piece of lore. Similar to a letter, but not used for displaying."""
  text = models.TextField()
  items = GenericRelation("SessionItem", related_query_name="lore")

class Image(DataItem):
  """It's an image. Literally read the name you fucking ape."""
  image_file = models.FileField(upload_to="images/")
  items = GenericRelation("SessionItem", related_query_name="image")

class Song(DataItem):
  """Music makes the world go round."""
  artist = models.CharField(max_length=255, blank=True)
  tags = models.ManyToManyField(Tag, blank=True)
  # Whether or not to loop the song continuously. This is generally true for
  # things like battle & ambient music.
  loop = models.BooleanField(default=False)
  sound_file = models.FileField(upload_to="music/")
  items = GenericRelation("SessionItem", related_query_name="song")

class Monster(DataItem):
  """Rawwwwwr"""
  image_file = models.FileField(upload_to="images/")
  items = GenericRelation("SessionItem", related_query_name="monster")

class City(DataItem):
  """A city!

  Cities are simply a numbered list of stuff, shops, houses, important buildings
  e.t.c. The number will correspond to an actual building on graph paper.
  Eventually things like shops will probably get some special handling, but
  for now it's just going to be text.
  """
  image_file = models.FileField(upload_to="images", blank=True)
  description = models.TextField(blank=True)
  items = GenericRelation("SessionItem", related_query_name="city")

class CityItem(models.Model):
  """A shop / house / point of interest in a city."""
  city = models.ForeignKey(City, on_delete=models.CASCADE)
  number = models.PositiveIntegerField()
  name = models.CharField(max_length=255, default=None, blank=True)
  text = models.TextField(default=None, blank=True)

  def __str__(self):
    return f"[{self.city.name}] {self.number} - {self.name}"

  class Meta:
    ordering = ["number"]

class Dungeon(DataItem):
  """A Dungeon!

  This is very similar to a city, only maintained as a separate data structure
  because they may diverge at some point.
  """
  image_file = models.FileField(upload_to="images", blank=True)
  description = models.TextField(blank=True)
  items = GenericRelation("SessionItem", related_query_name="dungeon")

class DungeonItem(models.Model):
  """A room in a dungeon."""
  dungeon = models.ForeignKey(Dungeon, on_delete=models.CASCADE)
  number = models.PositiveIntegerField()
  name = models.CharField(max_length=255, default=None, blank=True)
  text = models.TextField(default=None, blank=True)

  def __str__(self):
    return f"[{self.dungeon.name}] {self.number} - {self.name}"

  class Meta:
    ordering = ["number"]

class Campaign(models.Model):
  """A Campaign!

  A campaign won't have much data itself, but it will be comprised of multiple
  sessions. The actual session objects themselves will hold the necessary data.
  """
  name = models.CharField(max_length=255)
  flavor = models.TextField(default=None, blank=True)

  def __str__(self):
    return self.name

class Session(models.Model):
  """A Session!

  This is the real meat of the app. Sessions will contain two primary things:
  1. A whole bunch of data items: images to show to players, songs to play...
  2. A content field for planning out the session.
  """
  name = models.CharField(max_length=255)
  campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
  flavor = models.TextField(default=None, blank=True)
  content = models.TextField(default=None, blank=True)
  # Used for a post-session reflection.
  reflection = models.TextField(default=None, blank=True)

  def __str__(self):
    return self.name

class SessionItem(models.Model):
  session = models.ForeignKey(Session, on_delete=models.CASCADE)
  # By default generic relations look for a field named 'content_type' and
  # 'object_id'.
  content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
  object_id = models.PositiveIntegerField()
  item = GenericForeignKey()
  order = models.PositiveIntegerField()

  class Meta:
    ordering = ["order"]

gmhelper/panel/views.py
import collections
import random

from django.core import serializers
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render
from django.template import loader
from fuzzywuzzy import fuzz
from panel.models import Campaign, City, Image, Letter, Lore, Monster, Session, Song
from panel.serializers import *
from panel.constants import model_map
from rest_framework import generics

all_searchable_objects = [City, Image, Letter, Lore, Monster, Song]

def jaccard(a, b):
  return float(len(a.intersection(b))) / len(a.union(b))

def score(name, keyword):
  # Fucking nailed it.
  # We score based on two critieria:
  # 1. The fuzzy finding partial_ratio -- This is based on Levenshtein distance
  #      from the input keyword to the target movie title.  I.e. how many steps
  #      it takes to get from one to the other.  However, this by itself
  #      is not sufficient, as 'The Rings' is a perfect partial of a movie
  #      like 'The Lord of the Rings'.  The partial ratio is a number from
  #      0-100.
  # 2. Jaccard Coefficient of the character set.  We take the set of characters
  #      in the keyword and the movie title and take the length of their
  #      intersection divided by the length of their union.  This helps
  #      filter out only partially matching strings.  This returns a number
  #      from 0-1, we scale up to half the max value of the partial_ratio.
  keyword_l = keyword.lower()
  return fuzz.partial_ratio(name, keyword_l) + 50 * jaccard(set(keyword_l), set(name))

def auto_complete(request):
  keyword = request.GET["keyword"]
  data = []
  if keyword:
    data = [x for z in all_searchable_objects for x in z.objects.all()]
    data = sorted(data, key=lambda item: score(item.name.lower(), keyword), reverse = True)
  return JsonResponse(serializers.serialize("json", data[:5]), safe=False)

def info_card(request):
  """Render an info card for a given data item.

  This will render one of the card templates with the given item.
  """
  model = request.GET["model"]
  item_name = model.split(".")[1]
  item = model_map[model].objects.get(pk=request.GET["key"])
  return render(request, f"cards/{item_name}.html", {
    item_name: item,
    "no_cache": random.randint(1, 100000000)
  })

def display_item(request):
  """Render a full screen display for a given data item."""
  model = request.GET["model"]
  item_name = model.split(".")[1]
  item = model_map[model].objects.get(pk=request.GET["key"])
  return render(request, f"client/{item_name}.html", {
    item_name: item,
    "no_cache": random.randint(1, 100000000000)
  })


def songs(request):
  songs = Song.objects.order_by("name")
  return render(request, "songs.html", {"songs": songs})

def controls(request):
  campaigns = Campaign.objects.order_by("name")
  images = Image.objects.order_by("name")
  letters = Letter.objects.order_by("name")
  lores = Lore.objects.order_by("name")
  songs = Song.objects.order_by("name")
  if "campaign" not in request.session:
    request.session["campaign"] = campaigns[0].pk
  current_campaign = Campaign.objects.get(id=request.session["campaign"])
  sessions = current_campaign.session_set.all()
  if "session" not in request.session:
    request.session["session"] = sessions[0].pk
  print(request.session["campaign"])
  return render(request, "controls.html", {
    "campaigns": campaigns,
    "session": Session.objects.get(id=request.session["session"]),
    "sessions": sessions,
    "no_cache": random.randint(1, 100000000)
  })

def client(request):
  return render(request, "client.html", {
    "no_cache": random.randint(1, 100000000)
  })

class SongListCreate(generics.ListCreateAPIView):
  queryset = Song.objects.all()
  serializer_class = SongSerializer

gmhelper/panel/templates/card.html
{% load custom_filters %}
{% load static %}

<div id="si_{{si_id}}" class="card row">
  {% if class == "Image" or class == "City" or class == "Monster" %}
  <img class="card-image" src="{{item.image_file.url}}" />
  {% endif %}

  {% if class == "Letter" %}
  <h2 class="letter-title">{{item.name}}</h2>
  <p class="card-letter">
    {% if item.text|length >= 240 %}
    {{item.text|slice:":240"}}...
    {% else %}
    {{item.text}}
    {% endif %}
  {% endif %}

  {% if class == "Song" %}
  <h2 class="song-title">{{item.name}}</h2>
  <audio class="card-audio" id="song_{{item.pk}}" controls {% if item.loop %} loop {% endif %}>
    <source src="{{item.sound_file.url}}" />
  </audio>
  {% endif %}

  <div class="card-hover">
    <div class="row hover-row flex-center">
      {% if class == "Image" or class == "City" or class == "Dungeon" or class == "Monster" %}
      <h2 class="card-title">{{item.name}}</h2>
      {% endif %}
    </div>
    <div class="row hover-row flex-center">
      <button data-id="{{item.pk}}" data-model="panel.{{class|lower}}" class="delete-button hover-button flex-center">
        <img class="hover-icon" src="{% static "icons/trashcan.svg" %}" />
      </button>
      {% if class != "Song" and class != "Dungeon" %}
      <button data-id="{{item.pk}}" data-model="panel.{{class|lower}}" class="send-button hover-button flex-center">
        <img class="hover-icon" src="{% static "icons/arrow-right.svg" %}" />
      </button>
      {% endif %}
      {% if class == "Song" %}
      <button data-id="{{item.pk}}" class="play-button hover-button flex-center">
        <img class="hover-icon" src="{% static "icons/play.svg" %}" />
      </button>
      <button class="stop-button hover-button flex-center">
        <img class="hover-icon" src="{% static "icons/stop.svg" %}" />
      </button>
      {% endif %}
    </div>
  </div>
</div>

gmhelper/panel/templates/city.html
<h1>{{city.name}}</h1>

<div id="tabs_{{city.id}}">
  <ul>
    {% for item in city.cityitem_set.all %}
    <li><a href="#tabs-{{city.id}}-{{item.number}}">{{item.number}}{% if item.name %} - {{item.name}}{% endif %}</a></li>
    {% endfor %}
  </ul>
  {% for item in city.cityitem_set.all %}
  <div id="tabs-{{city.id}}-{{item.number}}">
    <p>{{item.text}}</p>
  </div>
  {% endfor %}
</div>

<!-- So this is a bit jank still, but since we convert newlines into <br />
     tags, scripts directly rendered onto the page won't work correctly unless
     they are on a single line. -->
<script>$(function() {$("#tabs_{{city.id}}").tabs();});</script>

gmhelper/panel/templates/client.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "css/client.css" %}?version={{no_cache}}" />

<div id="content">

</div>

<script src="{% static "js/jquery-3.4.1.js" %}"></script>
<script src="{% static "js/client.js" %}?version={{no_cache}}"></script>

gmhelper/panel/templates/controls.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/controls.css" %}?version={% now "U" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/jquery-ui.css" %}" />
    <script src="{% static "js/jquery-3.4.1.js" %}"></script>
    <script src="{% static "js/controls.js" %}?version={{no_cache}}"></script>
    <script src="{% static "js/bootstrap.min.js" %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static "js/jquery-ui.js" %}"></script>
  </head>
  <body>
    <div class="container-fluid main-content">
      <div class="row main-content">

        <div class="content-panel col-lg-9">
          <div class="content-controls">
            <button id="edit-session" class="control-button flex-center">
              <img class="icon-button" src="{% static "icons/pencil.svg" %}" />
              <img style="display:none" class="icon-button" src="{% static "icons/clippy.svg" %}" />
            </button>
          </div>
          <div class="session-content">
            {% include "session_content.html" with session=session %}
          </div>
        </div>

        <div class="session-panel col-lg-3">
          <div class="selectors">
            <div class="row selector-row flex-center">
              <select id="campaign-selector" class="pretty-select form-control">
                {% for campaign in campaigns %}
                  <option value="{{campaign.pk}}"
                  {% if campaign.pk == request.session.campaign %}
                  selected="selected"
                  {% endif %}
                  >{{campaign.name}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="row selector-row flex-center">
              <select id="session-selector" class="pretty-select form-control">
                {% for session in sessions %}
                  <option value="{{session.pk}}"
                  {% if session.pk == request.session.session %}
                  selected="selected"
                  {% endif %}
                  >{{session.name}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="auto-complete-input flex-center">
            <input type="text" id="input-keyword" class="form-control" placeholder="Search for stuff..." aria-label="Search for stuff...">
          </div>
          <div class="auto-complete">
            <ul id="auto-complete-results" class="auto-complete-ul">
            </ul>
          </div>
          <div class="session-items">
            {% include "session_panel.html" with images=images letters=letters songs=songs %}
          </div>
        </div>

      </div>
    </div>
  </body>
</html>

gmhelper/panel/templates/dungeon.html
<h1>{{dungeon.name}}</h1>

<div id="tabs_{{dungeon.id}}">
  <ul>
    {% for item in dungeon.dungeonitem_set.all %}
    <li><a href="#tabs-{{dungeon.id}}-{{item.number}}">{{item.number}}{% if item.name %} - {{item.name}}{% endif %}</a></li>
    {% endfor %}
  </ul>
  {% for item in dungeon.dungeonitem_set.all %}
  <div id="tabs-{{dungeon.id}}-{{item.number}}">
    <p>{{item.text}}</p>
  </div>
  {% endfor %}
</div>

<!-- So this is a bit jank still, but since we convert newlines into <br />
     tags, scripts directly rendered onto the page won't work correctly unless
     they are on a single line. -->
<script>$(function() {$("#tabs_{{dungeon.id}}").tabs();});</script>

gmhelper/panel/templates/session_content.html
{% load custom_filters %}

<div id="session-html">
  {{ session.content | custom_views | safe }}
</div>

<!--
  So as it turns out, if you use any whitespace in the textarea it will
  render that whitespace. Make sure the template tags have no extra spaces OR
  newlines.
-->
<textarea id="session-text" class="form-control">{{session.content}}</textarea>

gmhelper/panel/templates/session_panel.html
{% load custom_filters %}

{% for session_item in session.sessionitem_set.all %}
  {% include "card.html" with si_id=session_item.pk item=session_item.item class=session_item.item|class_name %}
{% endfor %}

{% for image in session.images.all|dictsort:"name" %}
  {% include "cards/image.html" with image=image %}
{% endfor %}

{% for letter in session.letters.all %}
  <h3>{{letter.name}}</h3>
  <button onclick="send_message({type: 'letter', text: '{{letter.text | escapejs}}'})">Send to Client</button>
{% endfor %}
<br /><br />
{% for song in session.songs.all|dictsort:"name" %}
  <h3 class="song-name">{{song.name}}</h3>
  <audio controls {% if song.loop %} loop {% endif %}>
    <source src="{{song.sound_file.url}}" />
  </audio>
  <br /><br />
{% endfor %}

gmhelper/panel/templates/songs.html
{% for song in songs %}
  <h3>{{song.name}}</h3>
  <ul>
    {% for tag in song.tags.all %}
      <li>{{tag.name}}</li>
    {% endfor %}
  </ul>
  <p>{{song.flavor}}</p>
  <audio controls {% if song.loop %} loop {% endif %}>
    <source src="{{song.sound_file.url}}" />
  </audio>
{% endfor %}